# curl -d grant_type=password
#-d username=user
#-d password=pass
#-H "Authorization: Basic dGVzdENsaWVudElkOnRlc3RTZWNyZXQ="
#-X POST http://localhost:8081/oauth/token
POST http://localhost:8081/oauth/token
Authorization: Basic dGVzdENsaWVudElkOnRlc3RTZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=user&password=pass

###

