# curl -X POST
#'http://localhost:8081/oauth/token'
#-H 'Authorization:Basic dGVzdENsaWVudElkOnRlc3RTZWNyZXQ='
#-d 'grant_type=authorization_code'
#-d 'code=u6q9Ju'
#-d 'redirect_uri=http://localhost:8081/oauth2/callback'
POST http://localhost:8081/oauth/token
Authorization: Basic Y2xpZW50OnBhc3M=
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=Du7o4g&redirect_uri=http://localhost:8081/oauth2/callback

###